version: '2'
services:
    stockwizard-app:
        image: stockwizard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://stockwizard-mysql:3306/stockwizard?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=stockwizard-elasticsearch:9300
        ports:
            - 8080:8080
    stockwizard-mysql:
        extends:
            file: mysql.yml
            service: stockwizard-mysql
    stockwizard-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: stockwizard-elasticsearch
